# Generated by Django 3.2.18 on 2023-04-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.TextField(max_length=255)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
