# Generated by Django 3.2.18 on 2023-05-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_auto_20230502_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuarios',
            new_name='id',
        ),
    ]
